<?php echo $this->doctype('HTML5'); ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <!--[if ie]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
  <title>Welcome to Mighty</title>
  <meta name="author" content="Greg Knapp http://gregk.me">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="/css/mighty.css" />
</head>
<body>
<div role="main" style="margin: 0 auto; width: 800px;">
  <?php echo $this->layout()->content; ?>
</div>
</body>
</html>
