<h1 style="text-align: center;">Welcome to Mighty</h1>
<p>Zend Framework is great, that's why I've used parts of it in Mighty.
However, Zend Framework is becoming increasingly heavy weight, and frankly
turning into a framework only a J2EE coder could love.</p>
<p>For smaller projects I created Mighty. Far simpler but still provides
structure for you to build your web application.</p>
<p><a href="https://github.com/gknapp">Mighty on github</a></p>
